#!/usr/bin/env bash

menu="rofi -dmenu -no-show-match"

stack=$(echo -e "$2" | tac)

#echo -e "stack: $stack;"

stack=$(echo -e "$stack\n$1\nf" | dc)

#echo -e "stack: $stack;"

[[ -n "$stack" ]] && stack="\n$stack"

action=$(echo -e "q$stack" | $menu -p "= ")

#echo "action: $action;"

case $action in
	"y") (echo -e "$(echo -e "$stack" | tac)\np" | dc) | wl-copy ; $0 "" "$stack" ;; # yank top to clipboard
	"p") $0 "" "$stack" ;; 
	"q") exit ;;
	"" ) exit ;;
	*  ) $0 "$action" "$stack" ;;
esac


