#!/usr/bin/env bash

menu="rofi -dmenu -no-show-match -monitor 0 -width 30"

stack=$(echo -e "$2" | tac)

#echo -e "stack: $stack;"

stack=$(echo -e "$stack\n$1\nf" | dc)

#echo -e "stack: $stack;"

[[ -n "$stack" ]] && prompt="$stack" || prompt="empty"

action=$(echo -e "$prompt" | $menu -p "= ")

#echo "action: $action;"

case $action in
	"y"    ) (echo -e "$(echo -e "$stack" | tac)\np" | dc) | wl-copy ; $0 "" "$stack" ;; # yank top to clipboard
	"p"    ) $0 "" "$stack" ;; 	
	"P"    ) $0 "s" "$stack" ;; 	
	"q"    ) exit ;;
	""     ) exit ;;
	"empty") $0 "" "" ;;
	*      ) $0 "$action" "$stack" ;;
esac


